name: Checkov Scan (Dev1)
on:
  pull_request:
    paths:
      - '.github/**'
      - 'infrastructure/**'

jobs:
  log-inputs:
    name: Log Workflow Parameters
    runs-on: ubuntu-latest
    steps:
      - name: Log Workflow Parameters
        run: |
          echo "Workflow Branch: ${{github.ref_name}}"
  dev1:
    name: Scan dev1
    uses: ./.github/workflows/_common-checkov-tf-scan-skip.yml
    with:
      environment: dev1
  qa:
    name: Scan qa1
    uses: ./.github/workflows/_common-checkov-tf-scan-skip.yml
    with:
      environment: qa1      